services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      # Maps a persistent local folder in your persistent workspaces directory to keep database data safe across stops
      - ./mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/ 
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  backend:
    build:
      dockerfile: Dockerfile
    working_dir: /app
    command: java -DServer.port=8080 -Dspring.data.mongodb.uri=mongodb://mongo:27017 -jar digimon-tcg-sim.jar
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: on-failure
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    ports:  
      - "5173:5173"
    environment:
      - WEBSOCKET_URL=wss://digimon-backend-774d.onrender.com/
    depends_on:
      - backend