// Fixes_and_Additions.js - Tamers & Options Restoration + Omnimon / LovelyAngemon Fixes
// Targets the singular collection: card

const purgeIds = [
  "BB1-019", "BB1-019_P1", "BB1-049", "BB1-084", "BB1-085", "BB1-086", 
  "BB1-086_P1", "BB1-087", "BB1-088", "BB1-089", "BB1-090", "BB1-091", 
  "BB1-093", "BB1-095", "BB1-096", "BB1-097", "BB1-098", "BB1-099", 
  "BB1-100", "BB1-101", "BB1-102", "BB1-104", "BB1-104_P1", "BB1-104_P2"
];

// Clear collection of target IDs to ensure no duplicates
db.card.deleteMany({ uniqueCardNumber: { $in: purgeIds } });

db.card.insertMany([
  // ==========================================
  // OMNIMON DNA FIXED EDITIONS (BB1-104)
  // ==========================================
  {
    "uniqueCardNumber": "BB1-104",
    "name": "Omnimon",
    "imgUrl": "/BB1-104.webp",
    "cardType": "Digimon",
    "color": ["White", "Blue", "Red"],
    "attribute": "Vaccine",
    "cardNumber": "BB1-104",
    "digivolveConditions": [
      { "color": "Blue", "cost": 5, "level": 6 },
      { "color": "Red", "cost": 5, "level": 6 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nerds] trait: 5 cost",
    "dnaDigivolve": "[DNA Digivolve] [Red]/[Yellow] Lv.6 + [Blue]/[Green] Lv.6\u00a0: Cost 0",
    "stage": "Mega",
    "digiType": ["Holy Knight", "Nerds", "IADA"],
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Partition {[WarGreymon] & [MetalGarurumon]}＞\n[When Digivolving][When Attacking][Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand or trash without paying its memory cost. If DNA digivolving, add 1 to the number of Digimon cards this effect can play.\n[All Turns][Once Per Turn] When any of your Digimon with the [Nerds] trait are played, 1 of your opponent's Digimon gets -5000 DP for each of your Digimon with the [Nerds] trait in play until the end of your opponent's turn.\n[All Turns] While you have [Nathan James] in play, all of your Level 5 or higher Digimon with the [Nerds] trait gain ＜Reboot＞.",
    "rule": null,
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Bandai",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-104_P1",
    "name": "Omnimon",
    "imgUrl": "/BB1-104_P1.webp",
    "cardType": "Digimon",
    "color": ["White", "Blue", "Red"],
    "attribute": "Vaccine",
    "cardNumber": "BB1-104",
    "digivolveConditions": [
      { "color": "Blue", "cost": 5, "level": 6 },
      { "color": "Red", "cost": 5, "level": 6 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nerds] trait: 5 cost",
    "dnaDigivolve": "[DNA Digivolve] [Red]/[Yellow] Lv.6 + [Blue]/[Green] Lv.6\u00a0: Cost 0",
    "stage": "Mega",
    "digiType": ["Holy Knight", "Nerds", "IADA"],
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Partition {[WarGreymon] & [MetalGarurumon]}＞\n[When Digivolving][When Attacking][Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand or trash without paying its memory cost. If DNA digivolving, add 1 to the number of Digimon cards this effect can play.\n[All Turns][Once Per Turn] When any of your Digimon with the [Nerds] trait are played, 1 of your opponent's Digimon gets -5000 DP for each of your Digimon with the [Nerds] trait in play until the end of your opponent's turn.\n[All Turns] While you have [Nathan James] in play, all of your Level 5 or higher Digimon with the [Nerds] trait gain ＜Reboot＞.",
    "rule": null,
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Bandai",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-104_P2",
    "name": "Omnimon",
    "imgUrl": "/BB1-104_P2.webp",
    "cardType": "Digimon",
    "color": ["White", "Blue", "Red"],
    "attribute": "Vaccine",
    "cardNumber": "BB1-104",
    "digivolveConditions": [
      { "color": "Blue", "cost": 5, "level": 6 },
      { "color": "Red", "cost": 5, "level": 6 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nerds] trait: 5 cost",
    "dnaDigivolve": "[DNA Digivolve] [Red]/[Yellow] Lv.6 + [Blue]/[Green] Lv.6\u00a0: Cost 0",
    "stage": "Mega",
    "digiType": ["Holy Knight", "Nerds", "IADA"],
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Partition {[WarGreymon] & [MetalGarurumon]}＞\n[When Digivolving][When Attacking][Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand or trash without paying its memory cost. If DNA digivolving, add 1 to the number of Digimon cards this effect can play.\n[All Turns][Once Per Turn] When any of your Digimon with the [Nerds] trait are played, 1 of your opponent's Digimon gets -5000 DP for each of your Digimon with the [Nerds] trait in play until the end of your opponent's turn.\n[All Turns] While you have [Nathan James] in play, all of your Level 5 or higher Digimon with the [Nerds] trait gain ＜Reboot＞.",
    "rule": null,
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Bandai",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // ==========================================
  // LOVELYANGEMON YELLOW/BLACK CORRECTION
  // ==========================================
  {
    "uniqueCardNumber": "BB1-049",
    "name": "LovelyAngemon",
    "imgUrl": "/BB1-049.webp",
    "cardNumber": "BB1-049",
    "cardType": "Digimon",
    "color": ["Yellow", "Black"],
    "attribute": "Vaccine",
    "stage": "Mega",
    "digiType": ["Warrior", "Arena"],
    "dp": 12000,
    "playCost": 12,
    "level": 6,
    "digivolveConditions": [
      { "color": "Yellow", "cost": 5, "level": 5 },
      { "color": "Black", "cost": 5, "level": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Arena] trait: 4 cost",
    "mainEffect": "＜Collision＞ ＜Barrier＞ ＜Piercing＞ ＜Blocker＞\n[All Turns] If one of your Digimon with the [Arena] trait would leave the battle area except by battle, by trashing your top security card, it does not leave.\n[All Turns][Once Per Turn] If a card is removed from your security stack, this Digimon gets +3000 DP until the end of your opponent's turn. Then, this Digimon may battle 1 of your opponent's Digimon.",
    "inheritedEffect": null,
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // ==========================================
  // MAGNAKIDMON Standard & Alt Art (BB1-019)
  // ==========================================
  {
    "uniqueCardNumber": "BB1-019",
    "name": "MagnaKidmon",
    "imgUrl": "/BB1-019.webp",
    "cardType": "Digimon",
    "color": ["Red"],
    "attribute": "Virus",
    "cardNumber": "BB1-019",
    "digivolveConditions": [
      { "color": "Red", "cost": 3, "level": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[IADA] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Dragonkin", "IADA"],
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "＜Rush＞ ＜Raid＞\n[On Play][When Attacking] Delete 1 of your opponent's Digimon with the lowest DP. If no Digimon was deleted by this effect, 1 of your Digimon with the [IADA] trait is unaffected by your opponent's Option cards and cannot have its DP reduced until the end of your opponent's turn.\n[All Turns] For each of your Tamers with the [IADA] trait with different names, this Digimon gets +1000 DP.",
    "digiXros": "[DigiXros\u00a0-2] Level 5 or lower Digimon cards with the [IADA] trait with different levels",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-019_P1",
    "name": "MagnaKidmon",
    "imgUrl": "/BB1-019_P1.webp",
    "cardType": "Digimon",
    "color": ["Red"],
    "attribute": "Virus",
    "cardNumber": "BB1-019",
    "digivolveConditions": [
      { "color": "Red", "cost": 3, "level": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[IADA] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Dragonkin", "IADA"],
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "＜Rush＞ ＜Raid＞\n[On Play][When Attacking] Delete 1 of your opponent's Digimon with the lowest DP. If no Digimon was deleted by this effect, 1 of your Digimon with the [IADA] trait is unaffected by your opponent's Option cards and cannot have its DP reduced until the end of your opponent's turn.\n[All Turns] For each of your Tamers with the [IADA] trait with different names, this Digimon gets +1000 DP.",
    "digiXros": "[DigiXros\u00a0-2] Level 5 or lower Digimon cards with the [IADA] trait with different levels",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // ==========================================
  // TAMERS
  // ==========================================
  {
    "uniqueCardNumber": "BB1-084",
    "name": "Nathan James",
    "imgUrl": "/BB1-084.webp",
    "cardType": "Tamer",
    "color": ["Red", "Blue", "White"],
    "attribute": null,
    "cardNumber": "BB1-084",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["Nerds", "IADA"],
    "dp": null,
    "playCost": 4,
    "level": null,
    "mainEffect": "[Start of Your Turn] If you have a Digimon with the [Nerds] or [IADA] trait in play, gain 1 memory.\n[End of Your Turn][Once Per Turn] By suspending this Tamer, ＜Draw 1＞. Then, 1 of your Level 5 or higher Digimon with the [Nerds] or [IADA] trait may attack.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-085",
    "name": "Director Watanabe",
    "imgUrl": "/BB1-085.webp",
    "cardType": "Tamer",
    "color": ["Blue", "Black"],
    "attribute": null,
    "cardNumber": "BB1-085",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["IADA"],
    "dp": null,
    "playCost": 5,
    "level": null,
    "mainEffect": "[Start of Your Turn] If you have 2 or less memory, set it to 3.\n[On Play] Reveal the top 3 cards of your deck. Add 1 card with the [IADA] trait from among them to your hand. Return the remaining cards to the bottom of your deck.\n[All Turns] When any of your other Tamers with the [IADA] trait are played, by suspending this Tamer, gain 1 memory.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-086",
    "name": "Laura Loath",
    "imgUrl": "/BB1-086.webp",
    "cardType": "Tamer",
    "color": ["Blue"],
    "attribute": null,
    "cardNumber": "BB1-086",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": [],
    "dp": null,
    "playCost": 4,
    "level": null,
    "mainEffect": "[Start of Your Turn] If you have 2 or less memory, set it to 3.\n[Your Turn] When one of your Blue Digimon with [Greymon] in its name suspends, by suspending this Tamer, you may use 1 Blue Option card with [Greymon] in its text without paying its memory cost.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-086_P1",
    "name": "Laura Loath",
    "imgUrl": "/BB1-086_P1.webp",
    "cardType": "Tamer",
    "color": ["Blue"],
    "attribute": null,
    "cardNumber": "BB1-086",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": [],
    "dp": null,
    "playCost": 4,
    "level": null,
    "mainEffect": "[Start of Your Turn] If you have 2 or less memory, set it to 3.\n[Your Turn] When one of your Blue Digimon with [Greymon] in its name suspends, by suspending this Tamer, you may use 1 Blue Option card with [Greymon] in its text without paying its memory cost.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-087",
    "name": "Cassidy Ibushi",
    "imgUrl": "/BB1-087.webp",
    "cardNumber": "BB1-087",
    "cardType": "Tamer",
    "color": ["Yellow", "Black"],
    "attribute": null,
    "stage": null,
    "digiType": ["DC"],
    "dp": null,
    "playCost": 4,
    "level": null,
    "digivolveConditions": [],
    "specialDigivolve": null,
    "mainEffect": "[On Play] [Start of Your Main Phase] If your opponent has a Digimon in play, gain 1 memory.\n[All Turns] When this Tamer suspends, for the turn, 1 of your Digimon gets +3000 DP and 1 of your opponent's Digimon gets -3000 DP. Then, 1 of your Digimon with the [DC] trait cannot be deleted by battle or have its digivolution cards trashed until the end of your opponent's turn.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-088",
    "name": "Dane Cathal",
    "imgUrl": "/BB1-088.webp",
    "cardType": "Tamer",
    "color": ["Yellow"],
    "attribute": null,
    "cardNumber": "BB1-088",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["IADA"],
    "dp": null,
    "playCost": 3,
    "level": null,
    "mainEffect": "[Start of Your Main Phase] If your opponent has a Digimon in play, gain 1 memory.\n[Your Turn] When any of your Digimon with the [IADA] trait suspend, by suspending this Tamer, 2 of your Digimon gain ＜Barrier＞.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-089",
    "name": "Leon Wilson",
    "imgUrl": "/BB1-089.webp",
    "cardType": "Tamer",
    "color": ["Green", "Purple"],
    "attribute": null,
    "cardNumber": "BB1-089",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["Nerds", "Arena"],
    "dp": null,
    "playCost": 5,
    "level": null,
    "mainEffect": "[Start of Your Turn] If your memory is 2 or less, set it to 3.\n[Your Turn] When one of your Digimon with the [Nerds] or [Arena] trait attacks, by suspending this Tamer, ＜Draw 1＞, then trash 1 card from your hand. Then, if attacking one of your opponent's Digimon, 1 of your Digimon may digivolve into 1 Digimon card with the [Arena] or [Nerds] trait in your trash with its digivolution cost reduced by 1.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-090",
    "name": "Oryon Sonier",
    "imgUrl": "/BB1-090.webp",
    "cardType": "Tamer",
    "color": ["Green", "Yellow"],
    "attribute": null,
    "cardNumber": "BB1-090",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["Nerds", "IADA"],
    "dp": null,
    "playCost": 4,
    "level": null,
    "mainEffect": "[Start of Your Main Phase] If you have a Digimon with the [Nerds] or [IADA] trait in play, gain 1 memory.\n[Your Turn] When any of your [Nerds] or [IADA] trait Digimon are played or digivolved, by suspending this Tamer, 1 of your Level 5 or higher [Nerds] or [IADA] trait Digimon gets ＜Alliance＞ for the turn.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-091",
    "name": "Taiyo James",
    "imgUrl": "/BB1-091.webp",
    "cardType": "Tamer",
    "color": ["Black", "Blue"],
    "attribute": null,
    "cardNumber": "BB1-091",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["CT"],
    "dp": null,
    "playCost": 5,
    "level": null,
    "mainEffect": "[Start of Your Turn] If your memory is 2 or less, set it to 3.\n[On Play] By trashing 1 card with the [CT] trait from your hand, ＜Draw 2＞.\n[Your Turn] When one of your Digimon with the [CT] trait would be played, by suspending this Tamer, reduce the cost by 1.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-093",
    "name": "Ridendo Fusco",
    "imgUrl": "/BB1-093.webp",
    "cardType": "Tamer",
    "color": ["Purple"],
    "attribute": null,
    "cardNumber": "BB1-093",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["CT"],
    "dp": null,
    "playCost": 3,
    "level": null,
    "mainEffect": "[Start of Your Main Phase] If you have a [CT] trait Option card in the battle area or face-up in your security stack, gain 1 memory.\n[Your Turn] When a [CT] trait Option card would be used, by suspending this Tamer, reduce the cost by 2.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // ==========================================
  // OPTIONS
  // ==========================================
  {
    "uniqueCardNumber": "BB1-095",
    "name": "Chaotic Thunder Tuning",
    "imgUrl": "/BB1-095.webp",
    "cardType": "Option",
    "color": ["Blue"],
    "attribute": null,
    "cardNumber": "BB1-095",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": [],
    "dp": null,
    "playCost": 3,
    "level": null,
    "mainEffect": "[Main] If you have a [Laura Loath] in play or in the digivolution cards of any of your Digimon, you may unsuspend 1 of your Digimon with [ShineGreymon] in its name, then place this card in the battle area.",
    "securityEffect": "[Security] Suspend 1 of your opponent's Digimon, then add this card to your hand.",
    "rule": "[All Turns] When one of your Blue Digimon with [Greymon] in its name would be deleted, ＜Delay＞ \n・You may play 1 Level 4 or lower Blue Digimon and 1 [Laura Loath] from that Digimon's digivolution cards without paying the cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-096",
    "name": "Driver City",
    "imgUrl": "/BB1-096.webp",
    "cardType": "Option",
    "color": ["Yellow", "Green"],
    "attribute": null,
    "cardNumber": "BB1-096",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["DC"],
    "dp": null,
    "playCost": 3,
    "level": null,
    "mainEffect": "＜Use Req. ([DC] trait)＞ \n[Main] Add your bottom security card to the hand and place this card face up as the bottom security card. Then you may play 1 [DC] trait card from your hand with the cost reduced by 3.",
    "securityEffect": "[Security] All your Digimon with the [DC] trait gain ＜Barrier＞ and ＜Piercing＞. All your Tamers with the [DC] trait gain ＜Rush＞.\n[Security] You may play 1 play cost 5 or lower [DC] trait card from your hand or trash without paying the cost.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-097",
    "name": "Digimon Wrestling Belt",
    "imgUrl": "/BB1-097.webp",
    "cardType": "Option",
    "color": ["Green", "Black"],
    "attribute": null,
    "cardNumber": "BB1-097",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["Arena"],
    "dp": null,
    "playCost": 3,
    "level": null,
    "mainEffect": "＜Use Req. ([Arena] trait)＞ \n[Main] Unsuspend 1 of your Digimon. Then, you may link this card to 1 of your Digimon without paying the cost.",
    "securityEffect": "[Security] Suspend 1 of your opponent's Digimon. Then, add this card to your hand.",
    "rule": null,
    "linkDP": 3000,
    "linkEffect": "[All Turns][Once Per Turn] When this Digimon wins a battle, trash the top card of your opponent's security stack.",
    "linkRequirement": "[Link] [Arena] trait: 2 cost",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-098",
    "name": "Deep Network",
    "imgUrl": "/BB1-098.webp",
    "cardType": "Option",
    "color": ["Black", "Purple"],
    "attribute": null,
    "cardNumber": "BB1-098",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["CT"],
    "dp": null,
    "playCost": 5,
    "level": null,
    "mainEffect": "＜Use Req. ([CT] trait)＞ \n[Security] [All Turns][Once Per Turn] When 1 of your level 6 or higher [CT] trait Digimon would be deleted, you may play 1 level 5 or lower [CT] trait Digimon card from that Digimon's digivolution cards without paying the cost.\n[Main] Add your bottom security card to your hand and place this card face up as your bottom security card. Then, you may play 1 [CT] trait Digimon card from your hand with its play cost reduced by 3.",
    "securityEffect": "[Security] You may play 1 level 4 or lower [CT] trait Digimon card from your hand or trash without paying the cost.",
    "rule": null,
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-099",
    "name": "Hell Training",
    "imgUrl": "/BB1-099.webp",
    "cardType": "Option",
    "color": ["Purple"],
    "attribute": null,
    "cardNumber": "BB1-099",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["Girlies"],
    "dp": null,
    "playCost": 2,
    "level": null,
    "mainEffect": "＜Use Req. ([Girlies] trait)＞ \n[Main] Reveal the top 2 cards of your deck. You may trash 1 [Girlies] trait card from among them. Return the rest to the bottom of the deck.\n[Main] ＜Delay＞ \n・1 of your Digimon may digivolve into a [Girlies] trait Digimon card in your trash with the cost reduced by 2.",
    "securityEffect": "[Security] You may trash 1 card in your hand. Then, place this card in the battle area.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-100",
    "name": "Puppetmaster",
    "imgUrl": "/BB1-100.webp",
    "cardNumber": "BB1-100",
    "cardType": "Option",
    "color": ["Purple", "Black"],
    "attribute": null,
    "stage": null,
    "digiType": ["CT"],
    "dp": null,
    "playCost": 4,
    "level": null,
    "digivolveConditions": [],
    "specialDigivolve": null,
    "mainEffect": "＜Use Req. ([CT] trait)＞ \n[Main] By trashing 1 card with the [CT] trait from your hand, place this card in the battle area.",
    "securityEffect": "[Security] Add this card to your hand.",
    "rule": "[Opponent's Turn] When an opponent's Digimon attacks, ＜Delay＞ \n・The attacking Digimon battles 1 of your opponent's other Digimon. Then, end the attack.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-101",
    "name": "The Fool",
    "imgUrl": "/BB1-101.webp",
    "cardNumber": "BB1-101",
    "cardType": "Option",
    "color": ["Purple", "Yellow"],
    "attribute": null,
    "stage": null,
    "digiType": ["CT"],
    "dp": null,
    "playCost": 3,
    "level": null,
    "digivolveConditions": [],
    "specialDigivolve": null,
    "mainEffect": "＜Use Req. ([CT] trait)＞ \n[Main] You may play 1 [Ghostmon] or 1 [Ridendo Fusco] from your hand or trash without paying its memory cost. Then, place this card in the battle area.",
    "securityEffect": "[Security] Activate this card's [Main] effects.",
    "rule": "[All Turns] When one of your Digimon with the [CT] trait would leave the battle area, ＜Delay＞ \n・You may play 1 [Fool] Token. (Digimon/Purple/4000 DP/＜Blocker＞ ＜Retaliation＞) If you do, change its original DP and colors to the original DP and colors of that Digimon.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-102",
    "name": "Resolution No. 256 of the 65th United Nations General Assembly, Agenda Item No. 102, the Charter of the International Agency of Digital Affairs",
    "imgUrl": "/BB1-102.webp",
    "cardType": "Option",
    "color": ["White"],
    "attribute": null,
    "cardNumber": "BB1-102",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["IADA"],
    "dp": null,
    "playCost": 3,
    "level": null,
    "mainEffect": "＜Use Req. ([IADA] trait)＞ \n[Main] You may play 1 Tamer card or Level 3 Digimon card with the [IADA] trait from your hand or trash without paying the cost. Then, place this card in the battle area.\n[Your Turn] When any of your Tamers with the [IADA] trait suspend, ＜Delay＞ \n・1 of your [IADA] trait Digimon may digivolve into a Digimon card with the [IADA] trait with the cost reduced by 1. For each of your [IADA] trait Tamers with different names, further reduce the cost by 1.",
    "securityEffect": "[Security] Activate this card's [Main] effects.",
    "restrictions": { "chinese": "Unrestricted", "english": "Unrestricted", "japanese": "Unrestricted", "korean": "Unrestricted" },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  }
]);

print("Successfully restored all Level 6, Level 7, Tamers, and Options with playtester formatting updates.");