// Updates.js - Corrects Omnimon Zwart Defeat and adds standard/alt-arts for the new images
// Target Collection: card

const batchIds = [
  "BB1-040", "BB1-042", "BB1-047_P1", "BB1-047_P2", 
  "BB1-073", "BB1-089", "BB1-097", "BB1-098"
];

// Delete previous versions before inserting the corrected/new records
db.card.deleteMany({ uniqueCardNumber: { $in: batchIds } });

db.card.insertMany([
  {
    "uniqueCardNumber": "BB1-073",
    "name": "Omnimon Zwart Defeat",
    "imgUrl": "/BB1-073.webp",
    "cardType": "Digimon",
    "color": ["Black", "Purple", "White"],
    "attribute": "Virus",
    "cardNumber": "BB1-073",
    "digivolveConditions": [
      { "color": "Black", "cost": 6, "level": 6 },
      { "color": "Purple", "cost": 6, "level": 6 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[CT] trait: 5 cost",
    "stage": "Mega",
    "digiType": ["Holy Warrior", "CT"],
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "[Execute]\n[When Digivolving] ＜De-Digivolve 1＞ all of your opponent's Digimon.\n[When Attacking][Once Per Turn] Delete 1 of your opponent's Digimon with a play cost of 5 or lower. For every 3 cards in this Digimon's digivolution cards, you may delete 1 additional of your opponent's Digimon with a play cost of 5 or lower.\n[On Deletion] You may play 1 Level 5 or lower Digimon card with the [CT] trait from your trash without paying its memory cost.",
    "inheritedEffect": null,
    "aceEffect": null,
    "burstDigivolve": null,
    "digiXros": null,
    "dnaDigivolve": null,
    "securityEffect": null,
    "rule": null,
    "linkDP": null,
    "linkEffect": null,
    "linkRequirement": null,
    "assemblyEffect": null,
    "restrictions": {
      "chinese": "Unrestricted",
      "english": "Unrestricted",
      "japanese": "Unrestricted",
      "korean": "Unrestricted"
    },
    "illustrator": "Bandai",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-040",
    "name": "Wankomon",
    "imgUrl": "/BB1-040.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "attribute": "Data",
    "cardNumber": "BB1-040",
    "digivolveConditions": [
      { "color": "Yellow", "cost": 1, "level": 2 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[IADA] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Beast", "IADA"],
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[Your Turn] When this Digimon would digivolve into a Digimon card with the [IADA] trait, reduce the digivolution cost by 1.",
    "inheritedEffect": "[All Turns][Once Per Turn] When any of your Tamers with the [IADA] trait suspend, give 1 of your opponent's Digimon -2000 DP for the turn.",
    "aceEffect": null,
    "burstDigivolve": null,
    "digiXros": null,
    "dnaDigivolve": null,
    "securityEffect": null,
    "rule": null,
    "linkDP": null,
    "linkEffect": null,
    "linkRequirement": null,
    "assemblyEffect": null,
    "restrictions": {
      "chinese": "Unrestricted",
      "english": "Unrestricted",
      "japanese": "Unrestricted",
      "korean": "Unrestricted"
    },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-042",
    "name": "Fangmon",
    "imgUrl": "/BB1-042.webp",
    "cardType": "Digimon",
    "color": ["Yellow", "Purple"],
    "attribute": "Data",
    "cardNumber": "BB1-042",
    "digivolveConditions": [
      { "color": "Yellow", "cost": 3, "level": 3 },
      { "color": "Purple", "cost": 3, "level": 3 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[IADA] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Dark Animal", "IADA"],
    "dp": 5000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[When Digivolving][When Attacking][Once Per Turn] If it is your turn, by trashing 1 card with the [IADA] trait from your hand, you may play 1 card with the [IADA] trait from your hand or trash with its play cost or use cost reduced by 2.\n[All Turns] While you have [Dane Cathal] in play, this Digimon gains ＜Guard＞.",
    "inheritedEffect": "[All Turns][Once Per Turn] When any of your Tamers with the [IADA] trait suspend, give 1 of your opponent's Digimon -2000 DP for the turn.",
    "aceEffect": null,
    "burstDigivolve": null,
    "digiXros": null,
    "dnaDigivolve": null,
    "securityEffect": null,
    "rule": null,
    "linkDP": null,
    "linkEffect": null,
    "linkRequirement": null,
    "assemblyEffect": null,
    "restrictions": {
      "chinese": "Unrestricted",
      "english": "Unrestricted",
      "japanese": "Unrestricted",
      "korean": "Unrestricted"
    },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-047_P1",
    "name": "Anubismon (Standard Art)",
    "imgUrl": "/BB1-047_P1.webp",
    "cardType": "Digimon",
    "color": ["Yellow", "Purple"],
    "attribute": "Vaccine",
    "cardNumber": "BB1-047",
    "digivolveConditions": [
      { "color": "Yellow", "cost": 4, "level": 5 },
      { "color": "Purple", "cost": 4, "level": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[IADA] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Shaman", "IADA"],
    "dp": 12000,
    "playCost": 12,
    "level": 6,
    "mainEffect": "＜Scapegoat＞\n[When Digivolving][End of Your Turn][Once Per Turn] You may play 1 Level 4 or lower Digimon card with the [IADA] trait from your trash without paying its memory cost.\n[All Turns] When you play another Digimon with the [IADA] trait, all of your Digimon with the [IADA] trait gain ＜Blocker＞ until the end of your opponent's turn.",
    "inheritedEffect": null,
    "aceEffect": null,
    "burstDigivolve": null,
    "digiXros": null,
    "dnaDigivolve": null,
    "securityEffect": null,
    "rule": null,
    "linkDP": null,
    "linkEffect": null,
    "linkRequirement": null,
    "assemblyEffect": null,
    "restrictions": {
      "chinese": "Unrestricted",
      "english": "Unrestricted",
      "japanese": "Unrestricted",
      "korean": "Unrestricted"
    },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-047_P2",
    "name": "Anubismon (Alt Art)",
    "imgUrl": "/BB1-047_P2.webp",
    "cardType": "Digimon",
    "color": ["Yellow", "Purple"],
    "attribute": "Vaccine",
    "cardNumber": "BB1-047",
    "digivolveConditions": [
      { "color": "Yellow", "cost": 4, "level": 5 },
      { "color": "Purple", "cost": 4, "level": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[IADA] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Shaman", "IADA"],
    "dp": 12000,
    "playCost": 12,
    "level": 6,
    "mainEffect": "＜Scapegoat＞\n[When Digivolving][End of Your Turn][Once Per Turn] You may play 1 Level 4 or lower Digimon card with the [IADA] trait from your trash without paying its memory cost.\n[All Turns] When you play another Digimon with the [IADA] trait, all of your Digimon with the [IADA] trait gain ＜Blocker＞ until the end of your opponent's turn.",
    "inheritedEffect": null,
    "aceEffect": null,
    "burstDigivolve": null,
    "digiXros": null,
    "dnaDigivolve": null,
    "securityEffect": null,
    "rule": null,
    "linkDP": null,
    "linkEffect": null,
    "linkRequirement": null,
    "assemblyEffect": null,
    "restrictions": {
      "chinese": "Unrestricted",
      "english": "Unrestricted",
      "japanese": "Unrestricted",
      "korean": "Unrestricted"
    },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-089",
    "name": "Leon Wilson",
    "imgUrl": "/BB1-089.webp",
    "cardType": "Tamer",
    "color": ["Green", "Purple"],
    "attribute": null,
    "cardNumber": "BB1-089",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["Nerds", "Arena"],
    "dp": null,
    "playCost": 5,
    "level": null,
    "mainEffect": "[Start of Your Turn] If your memory is 2 or less, set it to 3.\n[Your Turn] When one of your Digimon with the [Nerds] or [Arena] trait attacks, by suspending this Tamer, ＜Draw 1＞, then trash 1 card from your hand. Then, if attacking one of your opponent's Digimon, 1 of your Digimon may digivolve into 1 Digimon card with the [Arena] or [Nerds] trait in your trash with its digivolution cost reduced by 1.",
    "inheritedEffect": null,
    "aceEffect": null,
    "burstDigivolve": null,
    "digiXros": null,
    "dnaDigivolve": null,
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "rule": null,
    "linkDP": null,
    "linkEffect": null,
    "linkRequirement": null,
    "assemblyEffect": null,
    "restrictions": {
      "chinese": "Unrestricted",
      "english": "Unrestricted",
      "japanese": "Unrestricted",
      "korean": "Unrestricted"
    },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-097",
    "name": "Digimon Wrestling Belt",
    "imgUrl": "/BB1-097.webp",
    "cardType": "Option",
    "color": ["Green", "Black"],
    "attribute": null,
    "cardNumber": "BB1-097",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["Arena"],
    "dp": null,
    "playCost": 3,
    "level": null,
    "mainEffect": "＜Use Req. [Arena] trait＞\n[Main] Unsuspend 1 of your Digimon. Then, you may link this card to 1 of your Digimon without paying the cost.",
    "inheritedEffect": null,
    "aceEffect": null,
    "burstDigivolve": null,
    "digiXros": null,
    "dnaDigivolve": null,
    "securityEffect": "[Security] Suspend 1 of your opponent's Digimon. Then, add this card to your hand.",
    "rule": null,
    "linkDP": 3000,
    "linkEffect": "[All Turns][Once Per Turn] When this Digimon wins a battle, trash the top card of your opponent's security stack.",
    "linkRequirement": "[Link] [Arena] trait: 2 cost",
    "assemblyEffect": null,
    "restrictions": {
      "chinese": "Unrestricted",
      "english": "Unrestricted",
      "japanese": "Unrestricted",
      "korean": "Unrestricted"
    },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-098",
    "name": "Deep Network",
    "imgUrl": "/BB1-098.webp",
    "cardType": "Option",
    "color": ["Black", "Purple"],
    "attribute": null,
    "cardNumber": "BB1-098",
    "digivolveConditions": [],
    "specialDigivolve": null,
    "stage": null,
    "digiType": ["CT"],
    "dp": null,
    "playCost": 5,
    "level": null,
    "mainEffect": "＜Use Req. [CT] trait＞\n[Main] Add your bottom security card to your hand and place this card face up as your bottom security card. Then, you may play 1 [CT] trait Digimon card from your hand with its play cost reduced by 3.",
    "inheritedEffect": null,
    "aceEffect": null,
    "burstDigivolve": null,
    "digiXros": null,
    "dnaDigivolve": null,
    "securityEffect": "[Security] [All Turns][Once Per Turn] When 1 of your [CT] trait Digimon would be deleted, you may play 1 [CT] trait Digimon card from that Digimon's digivolution cards with a lower level than that Digimon without paying the cost.\n[Security] You may play 1 Level 4 or lower [CT] trait Digimon card from your hand or trash without paying its memory cost.",
    "rule": null,
    "linkDP": null,
    "linkEffect": null,
    "linkRequirement": null,
    "assemblyEffect": null,
    "restrictions": {
      "chinese": "Unrestricted",
      "english": "Unrestricted",
      "japanese": "Unrestricted",
      "korean": "Unrestricted"
    },
    "illustrator": "Original",
    "_class": "com.github.wekaito.backend.models.Card"
  }
]);

print("Standardized Omnimon Zwart Defeat and imported the latest batch of custom cards successfully.");